lib: [
  "_build/install/default/lib/regex_notation/META" {"META"}
  "_build/install/default/lib/regex_notation/opam" {"opam"}
  "_build/install/default/lib/regex_notation/regex_notation__Lexer.cmi"
  "_build/install/default/lib/regex_notation/regex_notation__Lexer.cmx"
  "_build/install/default/lib/regex_notation/regex_notation__Lexer.cmt"
  "_build/install/default/lib/regex_notation/lexer.ml"
  "_build/install/default/lib/regex_notation/regex_notation__Parser.cmi"
  "_build/install/default/lib/regex_notation/regex_notation__Parser.cmx"
  "_build/install/default/lib/regex_notation/regex_notation__Parser.cmt"
  "_build/install/default/lib/regex_notation/regex_notation__Parser.cmti"
  "_build/install/default/lib/regex_notation/parser.mli"
  "_build/install/default/lib/regex_notation/parser.ml"
  "_build/install/default/lib/regex_notation/regex_notation.cmi"
  "_build/install/default/lib/regex_notation/regex_notation.cmx"
  "_build/install/default/lib/regex_notation/regex_notation.cmt"
  "_build/install/default/lib/regex_notation/regex_notation.ml-gen"
  "_build/install/default/lib/regex_notation/regex_notation.cma"
  "_build/install/default/lib/regex_notation/regex_notation.cmxa"
  "_build/install/default/lib/regex_notation/regex_notation.a"
  "_build/install/default/lib/regex_notation/regex_notation.cmxs"
]
doc: [
  "_build/install/default/doc/regex_notation/README.md"
  "_build/install/default/doc/regex_notation/LICENSE"
]
