  $ . $ORIGINAL_DIR/tests/helpers/caml.sh

Can we access the RegexNotation module through a module 
generated by a functor application?

  $ caml $TESTDIR/functor_alias
  (Or (Or (String a) (String b)) (String c))

